dev_addr: 127.0.0.1:8080
strict: true
site_name: AirSim
site_dir: build
docs_dir: doc_root
repo_url: https://github.com/microsoft/airsim
#site_url: http://microsoft.github.io/airsim
#edit_uri: edit/master/docs
#repo_name: GitHub
site_description: 'Open source simulator based on Unreal Engine for autonomous vehicles from Microsoft AI & Research'

markdown_extensions:
  # - meta
  # - toc:
  #   permalink: true  # For ¶
  #   #permalink: "#"
  #   #separator: "_"
  # - admonition
  # - fenced_code 
  # - codehilite
  # - smarty
  # - tables
  # - def_list
  # - sane_lists
  # - codehilite:
  #   guess_lang: true
  #   linenums: true
  # - mdx_math:
  #       enable_dollar_delimiter: True
  # - pymdownx.highlight:
  #     guess_lang: true
  #     extend_pygments_lang:
  #     - name: php
  #       lang: php
  #       options:
  #         startinline: true  
  # - pymdownx.arithmatex:
  #       #inline_syntax: ['dollar']
  #       #block_syntax:  ['dollar', 'begin']
  #       #insert_as_script: True
  # # - pymdownx.keys:
  # #     strict: false        
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # #- pymdownx.critic
  # - pymdownx.details
  # - pymdownx.inlinehilite
  # - pymdownx.tasklist:
  #     custom_checkbox: true  
  # #- pymdownx.magiclink:
  # #-     base_repo_url: https://github.com/abinit/abinit
  # #-     repo_url_shortener: true
  # - pymdownx.mark
  # - pymdownx.smartsymbols:
  #       registered: false
  #       copyright: false
  #       care_of: false
  # - pymdownx.superfences
  # - pymdownx.tilde

remote_branch: gh-pages
#remote_name: origin

theme: 
  #name: 'rtd-dropdown'
  name: 'readthedocs'
  # Disable the default top left logo until we sort out our custom one.
  logo:
    icon: ' '
# extra_css:
#     - css/extra.css
#     - css/gallery.css
#     - css/my_codehilite.css

  # # Don't include MkDocs' JavaScript
  # include_search_page: false
  # search_index_only: true

extra:
  version: 1.2.1
  #previous_published_versions: [1.2.1] 
  #logo: images/logo-abinit-2015.svg
  feature:
      tabs: true
  palette:
      #primary: orange
      #accent: orange
      # primary: deep orange
      # accent: deep orange
      #primary: indigo
      #accent: indigo
  #font:
      #fonttext: 'Ubuntu'
      #fontcode: 'Ubuntu Mono'
  social:
      - type: facebook
        link: https://www.facebook.com/groups/1225832467530667/ 
      - type: github-alt
        link: https://github.com/Microsoft/AirSim
      # - type: twitter
      #   link: https://twitter.com/hashtag/abinit
      # - type: youtube
      #   link: https://www.youtube.com/watch?v=gcbfb_Mteo4

copyright: Copyright &copy; 2018 Microsoft Research

nav:
    - "Home": 'README.md'
    - "Whats New": 'CHANGELOG.md'
    - "Get AirSim":
      - "Download Binaries": 'docs/use_precompiled.md'
      - "Build on Windows": 'docs/build_windows.md'
      - "Build on Linux": 'docs/build_linux.md'
      - "Creating Custom Environment": 'docs/unreal_custenv.md'
    - "Using AirSim":
      - "Core APIs": 'docs/apis.md'
      - "Image APIs": 'docs/image_apis.md'
      - "C++ APIs": 'docs/apis_cpp.md'
      - "Development Workflow": 'docs/dev_workflow.md'
      - "Settings": 'docs/settings.md'
      - "Camera Views": 'docs/camera_views.md'      
      - "Using Car": 'docs/using_car.md'
      - "Remote Control": 'docs/remote_control.md'
      - "XBox Controller": 'docs/xbox_controller.md'
      - "Steering Wheel": 'docs/steering_wheel_installation.md'
      - "Multiple Vehicles": 'docs/multi_vehicle.md'
      - "Sensors": 'docs/sensors.md'
      - "LIDAR": 'docs/lidar.md'
      - "ROS": 'docs/ros.md'
      - "Playing Logs": 'docs/playback.md'
    - "Design":
      - "Architecture": 'docs/design.md'
      - "Code Structure": 'docs/code_structure.md'
      - "Coding Guidelines": 'docs/coding_guidelines.md'
      - "Flight Controller": 'docs/flight_controller.md'
      - "Simple Flight": 'docs/simple_flight.md'
      - "Hello Drone": 'docs/hello_drone.md'
    - "MavLink and PX4":
      - "PX4 Setup for AirSim": 'docs/px4_setup.md'
      - "PX4 in SITL": 'docs/px4_sitl.md'
      - "AirSim with Pixhawk": 'https://youtu.be/1oY8Qu5maQQ'
      - "PX4 Setup with AirSim": 'https://youtu.be/HNWdYrtw3f0'
      - "Debugging Attitude Estimation": 'https://www.youtube.com/watch?v=d_FyjKDWQfc&feature=youtu.be'
      - "Intercepting MavLink Messages": 'https://github.com/Microsoft/AirSim/wiki/Intercepting-MavLink-messages'
      - "Rapid Descent on PX4 Drones": 'https://github.com/Microsoft/AirSim/wiki/Rapid-Descent-on-PX4-drones'
      - "Building PX4": "docs/px4_build.md"
      - "PX4/MavLink Logging": 'docs/px4_logging.md'
      - "MavLink LogViewer": "docs/log_viewer.md"
      # - "MavLinkCom": 'MavLinkCom/README.md'
      # - "MavLink MoCap": 'MavLinkCom/MavLinkMoCap/Readme.md'
    - "Upgrading":
      - "Upgrading Unreal": 'docs/unreal_upgrade.md'
      - "Upgrading APIs": 'docs/upgrade_apis.md'
      - "Upgrading Settings": 'docs/upgrade_settings.md'
    - "Contributed Tutorials":
      - "Reinforcement Learning": 'docs/reinforcement_learning.md'
      - "Using Environments from Marketplace": 'https://www.youtube.com/watch?v=y09VbdQWvQY'
      - "Simple Collision Avoidance": 'https://github.com/simondlevy/AirSimTensorFlow'
      - "Autonomous Driving on Azure": 'https://aka.ms/AutonomousDrivingCookbook'
      - "Building Hexacopter": 'https://github.com/Microsoft/AirSim/wiki/hexacopter'
      - "Moving on Path Demo": 'https://github.com/Microsoft/AirSim/wiki/moveOnPath-demo'
      - "Building Point Clouds": 'https://github.com/Microsoft/AirSim/wiki/Point-Clouds'
      - "Surveying Using Drone": 'https://github.com/Microsoft/AirSim/wiki/Implementing-a-Drone-Survey-script'      
    - "Misc":
      - "AirSim on Real Drones": 'docs/custom_drone.md'
      - "Installing cmake on Linux": 'docs/cmake_linux.md'
      - "Tips for Busy HDD": 'docs/hard_drive.md'
      - "pfm format": 'docs/pfm.md'
      - "Setting up Unreal Environment": 'docs/unreal_proj.md'
      - "Blocks Environment": 'docs/unreal_blocks.md'
      - "Who is Using AirSim": 'docs/who_is_using.md'
      - "Working with UE Plugin Contents": 'docs/working_with_plugin_contents.md'
      - "Formula Student Technion Self-drive": 'https://github.com/Microsoft/AirSim/wiki/technion'
    - "Support": 
      - "FAQ": 'docs/faq.md'
      - "Support": 'SUPPORT.md'
      - "Create Issue": 'docs/create_issue.md'
      - "Contribute": 'CONTRIBUTING.md'


